# --- Configuración del Ambiente ---
# La URL de la página que vamos a probar
url=https://www.saucedemo.com/

# --- Credenciales de Prueba ---
# Estos son los datos que usará el método login()
valid_user=standard_user
valid_password=secret_sauce

# --- Configuración del Navegador (Opcional por ahora) ---
# Esto te servirá si luego quieres elegir el navegador desde aquí
browser=chrome